
name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

   

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
      
    - name: Github Action Merge Dependabot
  # You may pin to the exact commit or the version.
  # uses: fastify/github-action-merge-dependabot@1ce173cafbad45cb55d64a35613f54ad67fe3e7d
      uses: fastify/github-action-merge-dependabot@v3.3.0
    - name: .Net Build
  # You may pin to the exact commit or the version.
  # uses: EasyDesk/action-dotnet-build@d2c47d8701e3ea8db03dcabaacb37204fe123a22
      uses: EasyDesk/action-dotnet-build@v1.0.0
 
